[project]
name = "diffusiongen2"
version = "0.1.0"
dependencies = [
    "torch", "omegaconf", "hydra-core", "wandb"
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

